name: Maven build

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          docker build . -t java-app:latest
      
      - name: Run Docker Container
        run: |
          docker run -d -p 8080:8080 java-app:latest
          docker ps
          sleep 5
          docker exec java-app:latest curl http://localhost:8080/hello
        
